copyright: '© 2021-2077 Paladin Frosthaven'
site_name: 'FF06B5:CCRI'
repo_url: 'https://github.com/Frosthaven/cyberpunk-ff06b5-research'

extra_css:
  - 'assets/custom.css'

markdown_extensions:
  - toc:
      toc_depth: 0
  - attr_list
  - md_in_html

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - no-border
        - no-lightbox
      auto_caption: true
      caption_position: bottom
      background: white
      shadow: true

theme:
  logo: 'assets/logo.svg'
  favicon: 'assets/favicon.svg'
  name: material
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    scheme: slate
    primary: pink
    accent: yellow
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/141906786750955521
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/___Paladin___
