site_name: 'FF06B5:CCRF'
site_url: 'https://ff06b5.thedragon.dev'
repo_url: 'https://github.com/Frosthaven/cyberpunk-ff06b5-research'
domain: 'ff06b5.thedragon.dev'
extra_css:
  - 'assets/custom.css'

markdown_extensions:
  - attr_list
  - md_in_html
#plugins:
#  - glightbox
theme:
  logo: 'assets/logo.svg'
  favicon: 'assets/favicon.svg'
  name: material
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    scheme: slate
    primary: pink
    accent: yellow
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/141906786750955521
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/___Paladin___
